export interface dataDetailTrainingProps {
  id?: string;
  version?: number;
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
  updatedBy?: string;
  markForDelete?: boolean;
  bookingId?: string;
  title?: string;
  eventDatetime?: string;
  eventDateTimes?: eventDateTimesTypes[];
  coverImage?: string;
  alternateThumbnailUrl?: string;
  trainer?: detailTrainerTypes;
  host?: hostDetailTypes;
  trainerExternalName?: string;
  trainerExternalJobTitle?: string;
  trainerExternalDescription?: string;
  trainerExternalProfileImage?: string;
  category?: categoryDetailTypes;
  provider?: providerDetailTypes;
  maxCapacity?: number;
  participants?: number;
  status?: string;
  description?: string;
  finishedAt?: string;
  alreadyJoined?: boolean;
  trainingPrice?: number;
  location?: locationDetailTypes;
  blk?: boolean;
  level?: string;
  knowledgeGained?: string;
  termAndCondition?: string;
  trainingFAQs?: string[];
  minimumEducation?: string;
  gender?: string;
  age?: number;
  bank?: string;
  bankAccountNumber?: string;
  bankAccountName?: string;
  price?: number;
  language?: string;
  trainingObjective?: string;
  whatYouGetInfo?: string[];
  toolsUsed?: string[];
  multipleSession?: boolean;
  employerTraining?: boolean;
  online?: boolean;
  onlineClassLink?: string;
  onlineClassPassword?: string;
  tags?: string[];
  courseCode?: string;
  maximumAccessTimes?: number;
  storeLinks?: storeLinkTypes[];
  merchandise?: string;
  lmsCourseId?: string;
  jobCompetencyTargets?: string[];
  targetGroupOfParticipants?: string[];
  summary?: string;
  youtubeLink?: string;
  shortUrl?: string;
  currentRating?: number;
  numberOfReviewer?: number;
  reward?: string;
  manualCertificate?: boolean;
  certificateTemplate?: string;
  manualSignature?: boolean;
  signerName?: string;
  signerTitle?: string;
  signatureImage?: string;
  trainingCode?: string;
  productType?: string;
  deliveryType?: string;
  isLms?: boolean;
  showMerchandise?: boolean;
  showSyllabus?: boolean;
  trainingDetail?: any[];
  trainingMerchandise?: string;
  notes?: string;
  testimonialImageUrls?: string[];
  trainingBenefits?: trainingBenefitsTypes[];
  metaThumbnailTag?: string;
  metaDescription?: string;
  metaKeyword?: string[];
  metaTitle?: string;
  pmoCourseCode?: string;
  eventDateTime?: string;
}

export interface payloadDetailTraining {
  success: boolean;
  data: dataDetailTrainingProps;
  error?: string;
}

export type eventDateTimesTypes = {
  id?: any;
  start?: any;
  end?: any;
  active?: boolean;
};

export type detailTrainerTypes = {
  id?: any;
  version?: any;
  createdAt?: any;
  updatedAt?: any;
  createdBy?: any;
  updatedBy?: any;
  markForDelete?: boolean;
  identityNumber?: any;
  profileImage?: string;
  fullName?: string;
  email?: any;
  mobilePhone?: any;
  address?: any;
  provinceCode?: any;
  provinceName?: any;
  regencyCode?: any;
  postCode?: any;
  regencyName?: any;
  educationalAttainment?: any;
  degree?: any;
  interest?: any;
  expertise?: any;
  notes?: string;
  dob?: any;
  active?: boolean;
  roles?: any;
  providerId?: any;
  employerId?: any;
  gender?: any;
  firstTimeLogin?: boolean;
  verifiedTrainer?: boolean;
  needChangeEmail?: boolean;
  trainerApproval?: any;
  kkNumber?: any;
  clothesSize?: any;
  quote?: any;
  district?: any;
  districtName?: any;
  subDistrict?: any;
  subDistrictName?: any;
  professionalTitle?: any;
  houseNumber?: any;
  rtNumber?: any;
  rwNumber?: any;
  redemptionType?: any;
  currentReward?: any;
  loginCount?: any;
  addressInfo?: any;
  isJabodetabekAddress?: any;
  freePlanUsageCount?: any;
  changePassword?: any;
  registrationMethod?: any;
  userFlags?: any;
  referralCode?: any;
};

export type hostDetailTypes = {
  id?: string;
  fullName?: string;
  profileImage?: string;
  description?: string;
  employerTraining?: null;
};

export type categoryDetailTypes = {
  id?: string;
  version?: number;
  createdAt?: any;
  updatedAt?: any;
  createdBy?: string;
  updatedBy?: string;
  markForDelete?: boolean;
  code?: string;
  name?: string;
  type?: string;
  parent?: any;
};

export type locationDetailTypes = {
  provinceCode?: string;
  provinceName?: string;
  regencyCode?: string;
  regencyName?: string;
  address?: string;
  lng?: number;
  lat?: number;
};

export type providerDetailTypes = {
  id?: any;
  version?: any;
  createdAt?: any;
  updatedAt?: any;
  createdBy?: any;
  updatedBy?: any;
  markForDelete?: boolean;
  ownerName?: any;
  buildingAddress?: string;
  buildingStatus?: any;
  buildingImage?: any;
  buildingFacility?: any;
  buildingDescription?: any;
  buildingPhonenumber?: any;
  provinceCode?: string;
  provinceName?: string;
  regencyCode?: string;
  regencyName?: string;
  buildingSize?: number;
  landSize?: number;
  capacity?: number;
  lng?: number;
  lat?: number;
};

export type storeLinkTypes = {
  link?: string;
  channel?: string;
};

export type trainingBenefitsTypes = {
  id?: string;
  imageUrl?: string;
  description?: string;
  seq?: number;
};
